### Variáveis
@baseUrl = https://imperium-barbershop-api.dva83a.easypanel.host/v1/auth
@authToken = seu_token_jwt_aqui

@email = wrm.net@gmail.com
@password = Ss121212#

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

