### Enviar SMS
#@baseUrl = http://127.0.0.1:58055/v1
@baseUrl = https://imperium-barbershop-api.dva83a.easypanel.host/v1
@authToken = seu_token_jwt_aqui

POST {{baseUrl}}/sms
Content-Type: application/json

{
    "to": "+15088269012",
    "client": "Ramon",
    "service": [{
        "name": "Corte de Cabelo",
        "price": 50.00
    }],
    "appointmentDate": "2025-01-18T15:00:00.000Z",
    "barberName": "Wellington",
    "link": "https://imperiumbarbershop.com.br"
}
