### Enviar SMS
#@baseUrl = http://127.0.0.1:58055/v1
@baseUrl = https://imperium-barbershop-api.dva83a.easypanel.host/v1
@authToken = seu_token_jwt_aqui


POST {{baseUrl}}/sms/send
Content-Type: application/json

{
    "to": "+5521979299562",
    "client": "Ramon",
    "service": [{
        "name": "Corte de Cabelo",
        "price": 50.00
    }],
    "link": "https://imperiumbarbershop.com.br"
}
